---
title: "How to change a preemptive instance into an non-preemtive instance"
date: 2020-02-13 10:00:28 -0400
categories: fastai
---
## Before taking up the main subject
I was studying the ```fastai-lesson3``` copying [jupyter notebook of the lesson3](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-camvid.ipynb)

<br>
But, an error occurred.
<br>

![image](https://user-images.githubusercontent.com/47529632/74465592-8a1e2800-4e4a-11ea-9c4f-fd8992fb29bd.png)
![image](https://user-images.githubusercontent.com/47529632/74465720-c6ea1f00-4e4a-11ea-8501-0cecac575d3f.png)
![image](https://user-images.githubusercontent.com/47529632/74465770-db2e1c00-4e4a-11ea-88ca-8eb797a4e888.png)


## Trouble Shutting

First, i search what the error ```403 error``` is.

In [pytorch github issue](https://github.com/PetrochukM/PyTorch-NLP/issues/70), i figured out that the error occurred when the url does not exists or improper.

And then, i think, the error is occured downloading the .pth file(resnet34-333f7ec4.pth) when creating unet learner.

<br>

According to the log <br>
``` Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to C:\Users\david/.cache\torch\checkpoints\resnet34-333f7ec4.pth ```

I downloaded ```the .pth file``` directly using ```the url```(https://download.pytorch.org/models/resnet34-333f7ec4.pth) and moved ```the file``` into ```the directory```(C:\Users\david/.cache\torch\checkpoints)

After this, I runed ```the statement``` that create ```unet_learner``` and i checked that it is run without any trouble.


![image](https://user-images.githubusercontent.com/47529632/74467742-77a5ed80-4e4e-11ea-85d8-35a3c0600ef2.png)